# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  ghcr-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/InfinityFlowApp/index.json
    username: ${{secrets.GHCR_DEPENDABOT_PACKAGE_SECERET_USERNAME }}
    password: ${{secrets.GHCR_DEPENDABOT_PACKAGE_SECERET_KEY}}
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - ghcr-nuget
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      Temporal:
        patterns:
          - "Temporalio.*"
          - Temporalio
      Aspire:
        patterns:
          - "Aspire"
          - "Aspire.*"
      Kiota:
        patterns:
          - "Microsoft.Kiota*"
      dotnet:
        patterns:
          - "Microsoft.*"
          - "System.*"
        exclude-patterns:
          - "Microsoft.Orleans*"
          - "Microsoft.Kiota*"
      Orleans:
        patterns:
          - "Microsoft.Orleans.*"
          - "OrleansContrib.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      MartenAndFriends:
        patterns:
          - "Marten"
          - "WolverineFx"
          - "Marten.*"
          - "WolverineFx.*"
          - "JasperFx.*"
          - "Oakton.*"
          - "Lamar.*"

  - package-ecosystem: "devcontainers"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - "dev-tooling"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dev-tooling"
