// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace InfinityFlow.DigitalOcean.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApiBatchJobPhase
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BATCH_JOB_PHASE_UNKNOWN")]
        #pragma warning disable CS1591
        BATCH_JOB_PHASE_UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_JOB_PHASE_PENDING")]
        #pragma warning disable CS1591
        BATCH_JOB_PHASE_PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_JOB_PHASE_RUNNING")]
        #pragma warning disable CS1591
        BATCH_JOB_PHASE_RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_JOB_PHASE_SUCCEEDED")]
        #pragma warning disable CS1591
        BATCH_JOB_PHASE_SUCCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_JOB_PHASE_FAILED")]
        #pragma warning disable CS1591
        BATCH_JOB_PHASE_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_JOB_PHASE_ERROR")]
        #pragma warning disable CS1591
        BATCH_JOB_PHASE_ERROR,
        #pragma warning restore CS1591
    }
}
