// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace InfinityFlow.DigitalOcean.Client.Models
{
    /// <summary>
    /// Data Source configuration for Knowledge Bases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiKnowledgeBaseDataSource : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Name of storage bucket - Deprecated, moved to data_source_details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketName { get; set; }
#nullable restore
#else
        public string BucketName { get; set; }
#endif
        /// <summary>Creation date / time</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>File to upload as data source for knowledge base.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::InfinityFlow.DigitalOcean.Client.Models.ApiFileUploadDataSource? FileUploadDataSource { get; set; }
#nullable restore
#else
        public global::InfinityFlow.DigitalOcean.Client.Models.ApiFileUploadDataSource FileUploadDataSource { get; set; }
#endif
        /// <summary>Path of folder or object in bucket - Deprecated, moved to data_source_details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemPath { get; set; }
#nullable restore
#else
        public string ItemPath { get; set; }
#endif
        /// <summary>IndexingJob description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::InfinityFlow.DigitalOcean.Client.Models.ApiIndexingJob? LastIndexingJob { get; set; }
#nullable restore
#else
        public global::InfinityFlow.DigitalOcean.Client.Models.ApiIndexingJob LastIndexingJob { get; set; }
#endif
        /// <summary>Region code - Deprecated, moved to data_source_details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>Spaces Bucket Data Source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::InfinityFlow.DigitalOcean.Client.Models.ApiSpacesDataSource? SpacesDataSource { get; set; }
#nullable restore
#else
        public global::InfinityFlow.DigitalOcean.Client.Models.ApiSpacesDataSource SpacesDataSource { get; set; }
#endif
        /// <summary>Last modified</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Unique id of knowledge base</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::InfinityFlow.DigitalOcean.Client.Models.ApiKnowledgeBaseDataSource"/> and sets the default values.
        /// </summary>
        public ApiKnowledgeBaseDataSource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::InfinityFlow.DigitalOcean.Client.Models.ApiKnowledgeBaseDataSource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::InfinityFlow.DigitalOcean.Client.Models.ApiKnowledgeBaseDataSource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::InfinityFlow.DigitalOcean.Client.Models.ApiKnowledgeBaseDataSource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bucket_name", n => { BucketName = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "file_upload_data_source", n => { FileUploadDataSource = n.GetObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.ApiFileUploadDataSource>(global::InfinityFlow.DigitalOcean.Client.Models.ApiFileUploadDataSource.CreateFromDiscriminatorValue); } },
                { "item_path", n => { ItemPath = n.GetStringValue(); } },
                { "last_indexing_job", n => { LastIndexingJob = n.GetObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.ApiIndexingJob>(global::InfinityFlow.DigitalOcean.Client.Models.ApiIndexingJob.CreateFromDiscriminatorValue); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "spaces_data_source", n => { SpacesDataSource = n.GetObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.ApiSpacesDataSource>(global::InfinityFlow.DigitalOcean.Client.Models.ApiSpacesDataSource.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bucket_name", BucketName);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.ApiFileUploadDataSource>("file_upload_data_source", FileUploadDataSource);
            writer.WriteStringValue("item_path", ItemPath);
            writer.WriteObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.ApiIndexingJob>("last_indexing_job", LastIndexingJob);
            writer.WriteStringValue("region", Region);
            writer.WriteObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.ApiSpacesDataSource>("spaces_data_source", SpacesDataSource);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
