// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace InfinityFlow.DigitalOcean.Client.Models
{
    /// <summary>- MYSQL: MySQL- PG: PostgreSQL- REDIS: Redis- MONGODB: MongoDB- KAFKA: Kafka- OPENSEARCH: OpenSearch</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum App_database_spec_engine
    {
        [EnumMember(Value = "UNSET")]
        #pragma warning disable CS1591
        UNSET,
        #pragma warning restore CS1591
        [EnumMember(Value = "MYSQL")]
        #pragma warning disable CS1591
        MYSQL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PG")]
        #pragma warning disable CS1591
        PG,
        #pragma warning restore CS1591
        [EnumMember(Value = "REDIS")]
        #pragma warning disable CS1591
        REDIS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONGODB")]
        #pragma warning disable CS1591
        MONGODB,
        #pragma warning restore CS1591
        [EnumMember(Value = "KAFKA")]
        #pragma warning disable CS1591
        KAFKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPENSEARCH")]
        #pragma warning disable CS1591
        OPENSEARCH,
        #pragma warning restore CS1591
    }
}
