// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace InfinityFlow.DigitalOcean.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Droplet_backup_policy_record : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A boolean value indicating whether backups are enabled for the Droplet.</summary>
        public bool? BackupEnabled { get; set; }
        /// <summary>The backup_policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy? BackupPolicy { get; set; }
#nullable restore
#else
        public global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy BackupPolicy { get; set; }
#endif
        /// <summary>The unique identifier for the Droplet.</summary>
        public int? DropletId { get; set; }
        /// <summary>The next_backup_window property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::InfinityFlow.DigitalOcean.Client.Models.Droplet_next_backup_window? NextBackupWindow { get; set; }
#nullable restore
#else
        public global::InfinityFlow.DigitalOcean.Client.Models.Droplet_next_backup_window NextBackupWindow { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy_record"/> and sets the default values.
        /// </summary>
        public Droplet_backup_policy_record()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy_record"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy_record CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy_record();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backup_enabled", n => { BackupEnabled = n.GetBoolValue(); } },
                { "backup_policy", n => { BackupPolicy = n.GetObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy>(global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy.CreateFromDiscriminatorValue); } },
                { "droplet_id", n => { DropletId = n.GetIntValue(); } },
                { "next_backup_window", n => { NextBackupWindow = n.GetObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.Droplet_next_backup_window>(global::InfinityFlow.DigitalOcean.Client.Models.Droplet_next_backup_window.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("backup_enabled", BackupEnabled);
            writer.WriteObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.Droplet_backup_policy>("backup_policy", BackupPolicy);
            writer.WriteIntValue("droplet_id", DropletId);
            writer.WriteObjectValue<global::InfinityFlow.DigitalOcean.Client.Models.Droplet_next_backup_window>("next_backup_window", NextBackupWindow);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
